export const Orders = [
  {
    id: '1',
    title: 'Create React Landing Page',
    client: 'Sarah M.',
    clientImg: 'https://randomuser.me/api/portraits/women/65.jpg',
    amount: 150,
    dueDate: '2025-05-10',
    status: 'Active',
  },
  {
    id: '2',
    title: 'SEO Audit for Website',
    client: 'Mike D.',
    clientImg: 'https://randomuser.me/api/portraits/men/44.jpg',
    amount: 90,
    dueDate: '2025-05-07',
    status: 'Completed',
  },
  {
    id: '3',
    title: 'Design Logo Pack',
    client: 'Emma W.',
    // clientImg: 'https://randomuser.me/api/portraits/women/12.jpg',
    amount: 120,
    dueDate: '2025-05-11',
    status: 'Delivered',
  },
  {
    id: '4',
    title: 'Build E-commerce Website',
    client: 'John R.',
    clientImg: 'https://randomuser.me/api/portraits/men/52.jpg',
    amount: 450,
    dueDate: '2025-05-15',
    status: 'Active',
  },
  {
    id: '5',
    title: 'Write Blog Post about AI',
    client: 'Mark T.',
    clientImg: 'https://randomuser.me/api/portraits/men/31.jpg',
    amount: 60,
    dueDate: '2025-05-08',
    status: 'Active',
  },
  {
    id: '6',
    title: 'Create PowerPoint Presentation',
    client: 'Lily F.',
    clientImg: 'https://randomuser.me/api/portraits/women/21.jpg',
    amount: 100,
    dueDate: '2025-05-12',
    status: 'In Progress',
  },
  {
    id: '7',
    title: 'Design Marketing Materials',
    client: 'Rachel P.',
    clientImg: 'https://randomuser.me/api/portraits/women/75.jpg',
    amount: 180,
    dueDate: '2025-05-14',
    status: 'Cancelled',
  },
  {
    id: '8',
    title: 'Mobile App UI Design',
    client: 'David L.',
    clientImg: 'https://randomuser.me/api/portraits/men/85.jpg',
    amount: 250,
    dueDate: '2025-05-20',
    status: 'Active',
  },
  {
    id: '9',
    title: 'Translate French Document to English',
    client: 'Grace H.',
    clientImg: 'https://randomuser.me/api/portraits/women/53.jpg',
    amount: 50,
    dueDate: '2025-05-05',
    status: 'Completed',
  },
  {
    id: '10',
    title: 'Write Product Descriptions',
    client: 'James B.',
    clientImg: 'https://randomuser.me/api/portraits/men/24.jpg',
    amount: 75,
    dueDate: '2025-05-18',
    status: 'Delivered',
  },
];
